//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLinkCSharpClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLinkCSharpClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Address
        ///    {
        ///        public long a_Id { get; set; }
        ///        public string street { get; set; }
        ///        public int number { get; set; }
        ///        public string region { get; set; }
        ///        public int postalCode { get; set; }
        ///        public string country { get; set; }
        ///        public int countryCode { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Business_Order
        ///    {
        ///        public long bo_Id { get; set; }
        ///        public string organisation { get; set; }
        ///        public double orderTotal { get; set; }
        ///        public long business_policy_id { get; set; }
        ///        public long customer_id { get; set; }
        ///        public DateTime creationDate  { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Business_Order {
            get {
                return ResourceManager.GetString("Business_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Business_Policy
        ///    {
        ///        public long bp_Id { get; set; }
        ///        public string policyNumber { get; set; }
        ///        public string policyDescription { get; set; }
        ///        public string author { get; set; }
        ///        public DateTime lastUpdated { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Business_Policy {
            get {
                return ResourceManager.GetString("Business_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Customer
        ///    {
        ///        public long co_Id { get; set; }
        ///        public int numberOfOrders { get; set; }
        ///        public int creditcardNumber { get; set; }
        ///        public int bankAccountNumber { get; set; }
        ///        public int bankNumber { get; set; }
        ///        public float balance { get; set; }    
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Facility_Machine
        ///    {
        ///        public long fm_Id { get; set; }    
        ///        public int machineSerialId { get; set; } 
        ///        public int averageOutput { get; set; } 
        ///        public DateTime purchaseDate { get; set; } 
        ///        public long productionFacility_Id { get; set; } 
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Facility_Machine {
            get {
                return ResourceManager.GetString("Facility_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Facility_Output
        ///    {
        ///        public long fo_Id { get; set; }    
        ///        public string itemName { get; set; }    
        ///        public int outputAmount { get; set; }    
        ///        public DateTime outputDate { get; set; }    
        ///        public long productionFacility_Id { get; set; }    
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Facility_Output {
            get {
                return ResourceManager.GetString("Facility_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Order_Position
        ///    {
        ///        public long op_Id { get; set; }
        ///        public string name { get; set; }
        ///        public int size { get; set; }   
        ///        public double cost { get; set; }  
        ///        public int amount { get; set; }  
        ///        public long clientContract_Id { get; set; } 
        ///        public long productStorage_Id { get; set; } 
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Order_Position {
            get {
                return ResourceManager.GetString("Order_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Person
        ///    {
        ///        public long p_id { get; set; }
        ///        public string firstName { get; set; }
        ///        public string lastName { get; set; }
        ///        public DateTime dateOfBirth { get; set; }
        ///        public long address { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Position_Reference
        ///    {
        ///        public long pr_Id { get; set; }  
        ///        public string storageName { get; set; }  
        ///        public string storageAddress { get; set; }  
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Position_Reference {
            get {
                return ResourceManager.GetString("Position_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Production_ Chain
        ///    {
        ///        public long cm_Id { get; set; }
        ///        public string nameOfChain { get; set; }
        ///        public int executionTime { get; set; }
        ///        public int numberOfExecutions { get; set; }
        ///    }
        ///}   
        ///.
        /// </summary>
        internal static string Production_Chain {
            get {
                return ResourceManager.GetString("Production_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Production_Facility
        ///    {
        ///        public long pf_Id { get; set; }
        ///        public string facilityName { get; set; }
        ///        public string managerName { get; set; }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Production_Facility {
            get {
                return ResourceManager.GetString("Production_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CsharpSampleClient
        ///{
        ///    class Production_ Plan
        ///    {
        ///        public long pm_Id { get; set; }
        ///        public string planName { get; set; }
        ///        public DateTime creationDate { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string Production_Plan {
            get {
                return ResourceManager.GetString("Production_Plan", resourceCulture);
            }
        }
    }
}
